### ISSUE TITLE
need a screenshot for where is button at

### ISSUE THREAD

**Issue by bluelovers** [dneves/gitlab-integration-plugin#24]
need a screenshot for where is button at

im not sure is i didn't found this plugin menu or it it not work

**Comment by dneves** [comment]
what you mean?
there should be a tool window (in the bottom 'status bar') and if you search for 'gitlab' in the preferences window you should find the configuration settings panel

**Comment by bluelovers** [comment]
@dneves i know  preferences has this plugin's setting panel

just don't know where is this plugin at

thx for reply , now i see it

but , has new issues
looks like i still can't use

```
java.lang.NullPointerException
	at com.neon.intellij.plugins.gitlab.RetrofitSupplier.get(RetrofitSupplier.java:39)
	at com.neon.intellij.plugins.gitlab.GitLabServiceSupplier.get(GitLabServiceSupplier.java:17)
	at com.neon.intellij.plugins.gitlab.controller.GLIController.refresh(GLIController.java:117)
	at com.neon.intellij.plugins.gitlab.controller.GLIController.run(GLIController.java:48)
	at com.neon.intellij.plugins.gitlab.GitLabToolWindowFactory.createToolWindowContent(GitLabToolWindowFactory.java:20)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.ensureContentInitialized(ToolWindowImpl.java:530)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.getContentManager(ToolWindowImpl.java:354)
	at com.intellij.openapi.wm.impl.commands.RequestFocusInToolWindowCmd.processRequestFocus(RequestFocusInToolWindowCmd.java:50)
	at com.intellij.openapi.wm.impl.commands.RequestFocusInToolWindowCmd.run(RequestFocusInToolWindowCmd.java:42)
	at com.intellij.openapi.wm.impl.CommandProcessor.runNext(CommandProcessor.java:78)
	at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:59)
	at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableComman
```



my idea version is 2018.3.4
